## 异常

---

[TOC]

---

### 概述

![img](images/858860-20170911125844719-1230755033.png)

在 Java 中，所有的异常都有一个共同的祖先 java.lang 包中的 **Throwable 类**。Throwable： 有两个重要的子类：**Exception（异常）** 和 **Error（错误）** ，二者都是 Java 异常处理的重要子类，各自都包含大量子类。**异常能被程序本身处理，错误是无法处理。**



1. **Error（错误）:是程序无法处理的错误**，表示运行应用程序中较严重问题，**总是不可以控制的**，经常用来表示系统错误或低层资源的错误。大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。例如，Java 虚拟机运行错误（Virtual MachineError），当 JVM 不再有继续执行操作所需的内存资源时，将出现 OutOfMemoryError。这些异常发生时，Java 虚拟机（JVM）一般会选择线程终止

   这些错误表示故障发生于虚拟机自身、或者发生在虚拟机试图执行应用时，如 Java 虚拟机运行错误（Virtual MachineError）、类定义错误（NoClassDefFoundError）等。这些错误是不可查的，因为它们在应用程序的控制和处理能力之 外，而且绝大多数是程序运行时不允许出现的状况。对于设计合理的应用程序来说，即使确实发生了错误，本质上也不应该试图去处理它所引起的异常状况。在 Java 中，错误通过 Error 的子类描述。

2. **Exception（异常）:是程序本身可以处理的异常**，是可以被控制的或不可控制的，应该在应用程序级被处理。Exception 类有一个重要的子类 **RuntimeException**（由Java虚拟机抛出）

   **NullPointerException**（要访问的变量没有引用任何对象）

   **ArithmeticException**（算术运算符异常，如一个整数除以0）

   **ArrayIndexOutOfBoundsException**（下标越界异常）





### Error

---

- **抽象方法错误**。当应用试图调用抽象方法时抛出：java.lang.AbstractMethodError 断言错误，用来指示一个断言失败的情况：java.lang.AssertionError
- **类循环依赖错误**。在初始化一个类时，若检测到类之间循环依赖则抛出该异常：java.lang.ClassCircularityError
- **类格式错误**。当Java虚拟机试图从一个文件中读取Java类，而检测到该文件的内容不符合类的有效格式时抛出：java.lang.ClassFormatError
- **错误**。是所有错误的基类，用于标识严重的程序运行问题。这些问题通常描述一些不应被应用程序捕获的反常情况：java.lang.Error
- **初始化程序错误**。当执行一个类的静态初始化程序的过程中，发生了异常时抛出。静态初始化程序是指直接包含于类中的static语句段：java.lang.ExceptionInInitializerError
- **违法访问错误**。当一个应用试图访问、修改某个类的域（Field）或者调用其方法，但是又违反域或方法的可见性声明，则抛出该异常：java.lang.IllegalAccessError
- **不兼容的类变化错误**。当正在执行的方法所依赖的类定义发生了不兼容的改变时，抛出该异常。一般在修改了应用中的某些类的声明定义而没有对整个应用重新编译而直接运行的情况下，容易引发该错误：java.lang.IncompatibleClassChangeError
- **实例化错误**。当一个应用试图通过Java的new操作符构造一个抽象类或者接口时抛出该异常：java.lang.InstantiationError 内部错误。用于指示Java虚拟机发生了内部错误：java.lang.InternalError
- **链接错误**。该错误及其所有子类指示某个类依赖于另外一些类，在该类编译之后，被依赖的类改变了其类定义而没有重新编译所有的类，进而引发错误的情况：java.lang.LinkageError
- **未找到类定义错误**。当Java虚拟机或者类装载器试图实例化某个类，而找不到该类的定义时抛出该错误：java.lang.NoClassDefFoundError
- **域不存在错误**。当应用试图访问或者修改某类的某个域，而该类的定义中没有该域的定义时抛出该错误：java.lang.NoSuchFieldError
- **方法不存在错误**。当应用试图调用某类的某个方法，而该类的定义中没有该方法的定义时抛出该错误：java.lang.NoSuchMethodError
- **内存不足错误**。当可用内存不足以让Java虚拟机分配给一个对象时抛出该错误：java.lang.OutOfMemoryError
- **堆栈溢出错误**。当一个应用递归调用的层次太深而导致堆栈溢出时抛出该错误：java.lang.StackOverflowError
- **线程结束**。当调用Thread类的stop方法时抛出该错误，用于指示线程结束：java.lang.ThreadDeath
- **未知错误**。用于指示Java虚拟机发生了未知严重错误的情况：java.lang.UnknownError
- **未满足的链接错误**。当Java虚拟机未找到某个类的声明为native方法的本机语言定义时抛出：java.lang.UnsatisfiedLinkError
- **不支持的类版本错误**。当Java虚拟机试图从读取某个类文件，但是发现该文件的主、次版本号不被当前Java虚拟机支持的时候，抛出该错误：java.lang.UnsupportedClassVersionError
- **验证错误**。当验证器检测到某个类文件中存在内部不兼容或者安全问题时抛出该错误：java.lang.VerifyError
- **虚拟机错误**。用于指示虚拟机被破坏或者继续执行操作所需的资源不足的情况：java.lang.VirtualMachineError





### Exception

---

可分为运行时异常和非运行时异常(编译异常)

> 1. 所有的RuntimeException类及其子类的实例被称为运行时异常，其他的异常就是编译时异常
> 2. 编译(checked)异常: 除了RuntimeException及其子类以外，**其他的Exception类及其子类都属于可查异常**。Java程序必须显示处理，也就是说，当程序中可能出现这类异常，要么用try-catch语句捕获它，要么用throws子句声明抛出它，否则编译不会通过。
> 3. 运行时异常: 无需显示处理，也可以和编译时异常一样处理
>    - 不可查（unchecked）包括 **RuntimeException类及其子类异常和错误(Error)**。如NullPointerException(空指针异常)、IndexOutOfBoundsException(下标越界异常)等，这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生。运行时异常的特点是Java编译器不会检查它，也就是说，当程序中可能出现这类异常，即使没有用try-catch语句捕获它，也没有用throws子句声明抛出它，也会编译通过
> 4. 被检查的异常：Exception类本身，以及Exception的子类中除了"运行时异常"之外的其它子类都属于被检查异常。Java编译器会检查它。此类异常，要么通过throws进行声明抛出，要么通过try-catch进行捕获处理，否则不能通过编译。例如，CloneNotSupportedException就属于被检查异常。当通过clone()接口去克隆一个对象，而该对象对应的类没有实现Cloneable接口，就会抛出CloneNotSupportedException异常。



- **算术条件异常**（譬如：整数除零等）：java.lang.ArithmeticException
- **数组索引越界异常**。当对数组的索引值为负数或大于等于数组大小时抛出：java.lang.ArrayIndexOutOfBoundsException
- **数组存储异常**。当向数组中存放非数组声明类型对象时抛出：java.lang.ArrayStoreException
- **强制类型转换异常**。假设有类A和B（A不是B的父类或子类），O是A的实例，那么当强制将O构造为类B的- 实例时抛出该异常。该异常经常被称为强制类型转换异常：java.lang.ClassCastException
- **找不到类异常**。当应用试图根据字符串形式的类名构造类，而在遍历CLASSPAH之后找不到对应名称的class文件时，抛出该异常：java.lang.ClassNotFoundException
- **不支持克隆异常**。当没有实现Cloneable接口或者不支持克隆方法时,调用其clone()方法则抛出该异常：java.lang.CloneNotSupportedException
- **枚举常量不存在异常**。当应用试图通过名称和枚举类型访问一个枚举对象，但该枚举对象并不包含常量时，抛出该异常：java.lang.EnumConstantNotPresentException
- **根异常**。用以描述应用程序希望捕获的情况：java.lang.Exception
- **违法的访问异常**。当应用试图通过反射方式创建某个类的实例、访问该类属性、调用该类方法，而当时又无法访问类的、属性的、方法的或构造方法的定义时抛出该异常：java.lang.IllegalAccessException 违法的监控状态异常。当某个线程试图等待一个自己并不拥有的对象（O）的监控器或者通知其他线程等待该对象（O）的监控器时，抛出该异常：java.lang.IllegalMonitorStateException
- **违法的状态异常**。当在Java环境和应用尚未处于某个方法的合法调用状态，而调用了该方法时，抛出该异常：java.lang.IllegalStateException
- **违法的线程状态异常**。当线程尚未处于某个方法的合法调用状态，而调用了该方法时，抛出异常：java.lang.IllegalThreadStateException
- **索引越界异常**。当访问某个序列的索引值小于0或大于等于序列大小时，抛出该异常：java.lang.IndexOutOfBoundsException
- **实例化异常**。当试图通过newInstance()方法创建某个类的实例，而该类是一个抽象类或接口时，抛出该异常：java.lang.InstantiationException
- **被中止异常**。当某个线程处于长时间的等待、休眠或其他暂停状态，而此时其他的线程通过Thread的interrupt方法终止该线程时抛出该异常：java.lang.InterruptedException
- **数组大小为负值异常**。当使用负数大小值创建数组时抛出该异常：java.lang.NegativeArraySizeException
- **属性不存在异常**。当访问某个类的不存在的属性时抛出该异常：java.lang.NoSuchFieldException
- **方法不存在异常**。当访问某个类的不存在的方法时抛出该异常：java.lang.NoSuchMethodException 空指针异常。当应用试图在要求使用对象的地方使用了null时，抛出该异常。譬如：调用null对象的实例方法、访问null对象的属性、计算null对象的长度、使用throw语句抛出null等等：java.lang.NullPointerException
- **数字格式异常**。当试图将一个String转换为指定的数字类型，而该字符串确不满足数字类型要求的格式时，抛出该异常：java.lang.NumberFormatException
- **运行时异常**。是所有Java虚拟机正常操作期间可以被抛出的异常的父类：java.lang.RuntimeException 安全异常。由安全管理器抛出，用于指示违反安全情况的异常：java.lang.SecurityException 字符串索引越界异常。当使用索引值访问某个字符串中的字符，而该索引值小于0或大于等于序列大小时，抛出该异常：java.lang.StringIndexOutOfBoundsException
- **类型不存在异常**。当应用试图以某个类型名称的字符串表达方式访问该类型，但是根据给定的名称又找不到该类型是抛出该异常。该异常与ClassNotFoundException的区别在于该异常是unchecked（不被检查）异常，而ClassNotFoundException是checked（被检查）异常：java.lang.TypeNotPresentException 不支持的方法异常。指明请求的方法不被支持情况的异常：java.lang.UnsupportedOperationException



### 处理机制

---

#### Throwable

- **`public string getMessage()`**:返回异常发生时的简要描述
- **`public string toString()`**:返回异常发生时的详细信息
- **`public string getLocalizedMessage()`**:返回异常对象的本地化信息。使用 `Throwable` 的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与 `getMessage（）`返回的结果相同
- **`public void printStackTrace()`**:在控制台上打印 `Throwable` 对象封装的异常信息



异常总是先被抛出，后被捕捉

1. 子类重写父类方法时，子类的方法必须抛出相同的异常或父类异常的子类；
2. 如果父类抛出了多个异常,子类重写父类时,只能抛出相同的异常或者是他的子集,子类不能抛出父类没有的异常；
3. 如果被重写的方法没有异常抛出,那么子类的方法绝对不可以抛出异常,如果子类方法内有异常发生,那么子类只能try,不能throws。



#### try-catch-finally

----

```java
try    {
    可能出现问题的代码 ;//其中声明的变量出了try后不能被调用。其后可接零个或多个catch块，如果没有catch块，则必须跟一个finally块。
}catch(异常名 变量名){
    针对问题的处理 ;//一个 try 块可能有多个 catch 块。若如此，则执行第一个匹配块。即Java虚拟机会把实际抛出的异常对象依次和各个catch代码块声明的异常类型匹配，如果异常对象为某个异常类型或其子类的实例，就执行这个catch代码块，不会再执行其他的 catch代码块。catch中异常类型如果满足子父关系，则要求子类一定声明在父类的上面
}finally{
    释放资源;//一定会被执行。其后可接零个或多个catch块，如果没有catch块，则必须跟一个finally块。
}//像数据库连接、输入输出流、网络编程Socket等资源，JVM不能自动回收，需要手动进行资源的释放
```

> 1. catch关键字后面括号中的Exception类型的参数e。Exception就是try代码块传递给catch代码块的变量类型，e就是变量名。catch代码块中语句"e.getMessage();"用于输出错误性质。通常异常处理常用3个函数来获取异常的有关信息:
>
> 2. - getCause()：返回抛出异常的原因。如果 cause 不存在或未知，则返回 null。
>    - getMeage()：返回异常的消息信息。
>    - printStackTrace()：对象的堆栈跟踪输出至错误输出流，作为字段 System.err 的值。
>
> 3. finally是异常处理的统一出口，常用来实现资源释放，比如关闭文件，关于数据库连接等。不一定会被执行的。
>
>    在以下4种特殊情况下，finally块不会被执行：
>
>    - 1.在finally语句块中发生了异常。
>    - 2.在前面的代码中用了System.exit()退出程序。
>    - 3.程序所在的线程死亡。
>    - 4.关闭CPU。
>
> 4. 执行顺序：
>
>    - 1)当try没有捕获到异常时：try语句块中的语句逐一被执行，程序将跳过catch语句块，执行finally语句块和其后的语句；
>    - 2)当try捕获到异常，catch语句块里没有处理此异常的情况：当try语句块里的某条语句出现异常时，而没有处理此异常的catch语句块时，此异常将会抛给JVM处理，finally语句块里的语句**还是会被执行**，但finally语句块后的语句不会被执行；
>    - 3)当try捕获到异常，catch语句块里有处理此异常的情况：在try语句块中是按照**顺序**来执行的，当执行到某一条语句出现异常时，程序将跳到catch语句块，并与catch语句块逐一匹配，找到与之对应的处理程序，其他的catch语句块将不会被执行，而try语句块中，**出现异常之后的语句也不会被执行**，catch语句块执行完后，执行finally语句块里的语句，最后执行finally语句块后的语句；







#### throws

---

```java
static void pop() throws NegativeArraySizeException {
	// 定义方法并抛出NegativeArraySizeException异常
	int[] arr = new int[-3]; // 创建数组
}

public static void main(String[] args) { // 主方法
	try { // try语句处理异常信息
		pop(); // 调用pop()方法
	} catch (NegativeArraySizeException e) {
		System.out.println("pop()方法抛出的异常");// 输出异常信息
	}
}
使用throws关键字将异常抛给调用者后，如果调用者不想处理该异常，可以继续向上抛出，但最终要有能够处理该异常的调用者。
pop方法没有处理异常NegativeArraySizeException，而是由main函数来处理。
```



- 用在方法声明后面，跟的是异常类名
- 可以跟多个异常类名，用逗号隔开
- 表示抛出异常，由该方法的调用者来处理
- throws表示出现异常的一种可能性，并不一定会发生这些异常



> Throws抛出异常的规则如下所示：
>
> - 1)如果是不可查异常（unchecked exception），即Error、RuntimeException或它们的子类，那么可以不使用throws关键字来声明要抛出的异常，编译仍能顺利通过，但在运行时会被系统抛出。
> - 2)必须声明方法可抛出的任何可查异常（checked exception）。即如果一个方法可能出现受可查异常，要么用try-catch语句捕获，要么用throws子句声明将它抛出，否则会导致编译错误
> - 3)仅当抛出了异常，该方法的调用者才必须处理或者重新抛出该异常。当方法的调用者无力处理该异常的时候，应该继续抛出，而不是囫囵吞枣。
> - 4)调用方法必须遵循任何可查异常的处理和声明规则。若覆盖一个方法，则不能声明与覆盖方法不同的异常。声明的任何异常必须是被覆盖方法所声明异常的同类或子类。



##### throw

格式：`throw ThrowableInstance`

ThrowableInstance必须是Throwable或其子类类型的对象。throw语句之后的执行流程会立即停止，所有的后续语句都不会执行，然后按顺序依次检查所有的catch语句，检查是否和异常类型相匹配。如果没有找到匹配的catch语句，那么默认的异常处理程序会终止程序并输出堆栈踪迹。

```java
public class Demo {
	public static void demo(){
		throw new NullPointerException("NullPointer");
	}

	public static void main(String[] args) {
		try{
			demo();
		}catch (NullPointerException e) {
			System.out.println("NullPointerException");//NullPointerException
		}//如果catch子句的异常与throw抛出的异常类型不匹配时，异常将由Java默认的异常处理程序来处理
	}
}
```

throw的具体使用方法

- 用在方法体内，跟的是异常对象名
- 只能抛出一个异常对象名
- 表示抛出异常，由方法体内的语句处理

> throw的概述以及和throws的区别
>
> - throws的方式处理异常: 定义功能方法时，需要把出现的问题暴露出来让调用者去处理。那么就通过throws在方法上标识。
> - throw的概述: 在功能方法内部出现某种情况，程序不能继续运行，需要进行跳转时，就用throw把异常对象抛出。





### 自定义异常

---

- 使用Java内置的异常类可以描述在编程时出现的大部分异常情况。除此之外，用户还可以自定义异常。用户自定义异常类，只需**继承Exception类**即可。
- 在程序中使用自定义异常类，大体可分为以下几个步骤。
  - （1）创建自定义异常类。
  - （2）在方法中通过throw关键字抛出异常对象。
  - （3）如果在当前抛出异常的方法中处理异常，可以使用try-catch语句捕获并处理；否则在方法的声明处通过throws关键字指明要抛出给方法调用者的异常，继续进行下一步操作。
  - （4）在出现异常方法的调用者中捕获并处理异常。